apiVersion: v1
kind: Namespace
metadata:
  name: test  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octopus-test
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octopus-test-role
  namespace: test
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octopus-test-role-binding
subjects:
- namespace: test
  kind: ServiceAccount
  name: octopus-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octopus-role
---
apiVersion: v1
kind: Secret
metadata:
  name: octopus-test-token
  namespace: test
  annotations:
    kubernetes.io/service-account.name: octopus-test
type: kubernetes.io/service-account-token