apiVersion: v1
kind: Secret
metadata:
  name: trident-credentials
type: Opaque
stringData:
  connectionString: "blah"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: trident-web
  template:
    metadata:
      labels:
        component: trident-web
    spec:
      containers:
        - name: trident-web
          image: bobjwalker99/trident:latest
          ports:
           - containerPort: 5000
             name: http-port
          env:
           - name: TRIDENT_CONNECTION_STRING
             valueFrom:
               secretKeyRef:
                 name: trident-credentials
                 key: connectionString
---
apiVersion: v1
kind: Service
metadata:
  name: trident-loadbalancer-service
spec:
  selector:
    component: trident-web
  ports:
    - port: 5000
      targetPort: 5000
      name: http-port
  type: LoadBalancer
              