apiVersion: v1
kind: Secret
metadata:
  name: trident-credentials
type: Opaque
stringData:
  connectionString: "blah"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: trident-web
  template:
    metadata:
      labels:
        component: trident-web
    spec:
      containers:
        - name: trident-web
          image: bobjwalker99/trident:latest
          imagePullPolicy: "Always"
          ports:
           - containerPort: 5000
             name: http-port
          env:
           - name: TRIDENT_CONNECTION_STRING
             valueFrom:
               secretKeyRef:
                 name: trident-credentials
                 key: connectionString
---
apiVersion: v1
kind: Service
metadata:
  name: trident-app-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: trident-web
  ports:
    - port: 6800
      targetPort: 5000  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trident-ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: trident.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trident-app-cluster-ip-service
                port:
                  number: 6800

              