apiVersion: v1
kind: Service
metadata:
  name: trident-loadbalancer-service
spec:
  selector:
    component: trident-web
  ports:
    - port: 5000
      targetPort: 5000
      name: http-port
  type: LoadBalancer