apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
 - target:
    kind: Deployment
    name: trident-deployment.yaml
   path: trident-app.yaml
 - target:
    kind: Service
    name: trident-app-cluster-ip-service
   path: trident-app-cluster-ip-service.yaml
 - target:
    kind: Ingress
    name: trident-ingress-nginx
   path: trident-ingress-nginx.yaml