apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

secretGenerator:
  - name: trident-credentials
    literals:
      - connectionString="blah"

images:
 - name: bobjwalker99/trident
   newName: bobjwalker99/trident
   newTag: "3.4.0.357"

patches:
 - target:
    kind: Ingress
    name: trident-ingress-nginx
   path: trident-ingress-nginx.yaml