apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

patches:
 - target:
    kind: Ingress
    name: trident-ingress-nginx
   path: trident-ingress-nginx.yaml