apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- trident-deployment.yaml
- trident-app-cluster-ip-service.yaml
- trident-ingress-nginx.yaml

secretGenerator:
  - name: trident-credentials
    literals:
      - connectionString="server=localhost;integrated security=true;database=trident"

images:
 - name: bobjwalker99/trident
   newName: bobjwalker99/trident
   newTag: "latest"