apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- trident-deployment.yaml
- trident-app-cluster-ip-service.yaml
- trident-ingress-nginx.yaml

secretGenerator:
  - name: trident-credentials
    literals:
      - connectionString="#{Project.Connection.String}"

images:
 - name: trident-web
   newName: bobjwalker/trident
   newTag: #{Octopus.Release.Number}