apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: trident-credentials
    namespace: #{Project.K8s.Namespace}
    literals:
      - connectionstring="#{Project.Connection.String}"

resources:
- trident-deployment.yaml
- trident-app-cluster-ip-service.yaml
- trident-ingress-nginx.yaml