apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- trident-deployment.yaml

images:
 - name: bobjwalker99/trident
   newName: bobjwalker99/trident
   newTag: "#{Project.K8s.Image.VersionTag}"