apiVersion: v1
kind: Secret
metadata:
  name: trident-credentials
type: Opaque
stringData:
  connectionString: "blah"
  sumologicUrl: "blah"
  instanceUrl: "blah"
  instanceApiKey: "blah"
  environment: "Development"
