apiVersion: v1
kind: Secret
metadata:
  name: trident-credentials
type: Opaque
stringData:
  connectionString: "blah"
  instanceUrl: "blah"
  instanceApiKey: "blah"
  sumoLogicUrl: "blah"
  featureTogglesClientId: "blah"
  environmentName: "Production"