name: PR Closed

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

env:    
  OCTOPUS_PROJECT_NAME: ${{ vars.OCTOPUS_PROJECT_NAME }}
  OCTOPUS_RUNBOOK_NAME: "Destroy Application Infrastructure"
  OCTOPUS_ENVIRONMENT_NAME: "Development"
  OCTOPUS_SPACE: Default
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUSSERVERAPIKEY }}  
  OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
jobs:
  destroy-feature-branch:       
    runs-on: ubuntu-latest        
    steps:
      - name: run destroy infrastructure runbook
        uses: OctopusDeploy/run-runbook-action@v3
        with:
          project: ${{ env.OCTOPUS_PROJECT_NAME }}          
          runbook: "${{ env.OCTOPUS_RUNBOOK_NAME }}"
          environments: "${{ env.OCTOPUS_ENVIRONMENT_NAME }}"  
          variables: "Project.Release.Branch.Name:${{ github.head_ref || github.ref }}"
