name: PR Closed

on:
  workflow_dispatch:

env:    
  OCTOPUS_PROJECT_NAME: ${{ vars.OCTOPUS_PROJECT_NAME }}
  OCTOPUS_RUNBOOK_NAME: "Destroy Application Infrastructure"
  OCTOPUS_ENVIRONMENT_NAME: "Development"
  OCTOPUS_SPACE: Default
  OCTOPUS_OIDC_SERVICE_ACCOUNT: ${{ secrets.OCTOPUS_OIDC_SERVICE_ACCOUNT_ID }}   
  OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
jobs:
  destroy-feature-branch:       
    runs-on: ubuntu-latest  
    permissions:
      # Add any additional permissions your job requires here
      id-token: write # This is required to obtain the ID token from GitHub Actions     
    steps:
      - name: Login to Octopus Deploy 
        uses: OctopusDeploy/login@v1
        with: 
          server: ${{ env.OCTOPUS_URL }}
          service_account_id: ${{ env.OCTOPUS_OIDC_SERVICE_ACCOUNT}}

      - name: run destroy infrastructure runbook
        uses: OctopusDeploy/run-runbook-action@v3
        with:
          project: ${{ env.OCTOPUS_PROJECT_NAME }}          
          runbook: "${{ env.OCTOPUS_RUNBOOK_NAME }}"
          environments: "${{ env.OCTOPUS_ENVIRONMENT_NAME }}"  
          git_ref: ${{ (github.ref_type == 'tag' && github.event.repository.default_branch ) || (github.ref || github.head_ref) }}
          git_commit: ${{ github.event.after || github.event.pull_request.head.sha }} 
