name: spin the Version

on:
    workflow_dispatch:
jobs:
    no_op_build:
        runs-on: ubuntu-latest                
        steps:
            - uses: actions/checkout@v1
              with:
                fetch-depth: '0'            
            - uses: actions/checkout@v1
              with:
                fetch-depth: '0'            
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v1
              with:
                  versionSpec: 6.x
            - id: determine_version
              name: Determine Version
              uses: gittools/actions/gitversion/execute@v1
              with:
                  additionalArguments: /config gitversion.yml
            - name: update version file with latest version
              uses: mikefarah/yq@master              
              with:
                cmd: yq -i '.runNumber = "${{ steps.determine_version.outputs.FullSemVer }}"' 'version.yml' 
            - name: update version file with latest run number
              uses: mikefarah/yq@master              
              with:
                cmd: yq -i '.runNumber = "${{ github.run_number }}"' 'version.yml'              
            - id: commit_file_change
              name: commit file change
              run : |
                git config --global user.name '${{ github.actor }}'
                git config --global user.email '${{ github.actor }}@users.noreply.github.com'
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY                

                git checkout "${GITHUB_REF:11}" 
                git stage 'version.yml'
                git commit -am "Updating prvious version to ${{ steps.determine_version.outputs.FullSemVer }} and run number to ${{ github.run_number }}"
                git push --set-upstream origin ${GITHUB_REF:11}                  
